Traceback (most recent call last):
  File "/home/phil/mini38/envs/work/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/phil/mini38/envs/work/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/phil/mini38/envs/work/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/phil/mini38/envs/work/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/phil/mini38/envs/work/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/phil/mini38/envs/work/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/home/phil/mini38/envs/work/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/phil/mini38/envs/work/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from numpy.testing import assert_almost_equal

Temps = np.asarray([300.0, 280.0, 270.0, 260.0])
taus = np.asarray([0.0, 0.2, 0.35, 0.5, 0.6])
Tsfc = 305.0
the_wavel = 10.0e-6
out = multi_layer_radiance(Tsfc, Temps, taus, the_wavel)
assert_almost_equal(out * 1.0e-6, 9.045, decimal=3)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-069a65bb1c32>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0mthe_wavel[0m [0;34m=[0m [0;36m10.0e-6[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0mout[0m [0;34m=[0m [0mmulti_layer_radiance[0m[0;34m([0m[0mTsfc[0m[0;34m,[0m [0mTemps[0m[0;34m,[0m [0mtaus[0m[0;34m,[0m [0mthe_wavel[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0massert_almost_equal[0m[0;34m([0m[0mout[0m [0;34m*[0m [0;36m1.0e-6[0m[0;34m,[0m [0;36m9.045[0m[0;34m,[0m [0mdecimal[0m[0;34m=[0m[0;36m3[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mTypeError[0m: unsupported operand type(s) for *: 'NoneType' and 'float'
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

